fieldLayouts:
  fa2f8688-6d65-4f10-9f0e-c376dff50a68:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8a325790-ed1c-412f-8e50-679266127667
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Intro
            type: craft\fieldlayoutelements\Heading
            uid: 537cc337-9c35-42e6-a4e4-843811f8cb15
            userCondition: null
          -
            elementCondition: null
            fieldUid: 8fa4ab2b-d31b-4bd6-b6d8-ee2df12c14e5 # Afbeelding 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9a5d68f-191e-4614-a919-1bc00f772ed4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e68f4e12-33a8-4163-adbb-26bfa484de3a # Redactor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ad7c559-acaf-40c8-9625-6fe6d335c729
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02f25b1a-2d32-4626-8ab1-ed9e9f3dae3d # Link 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b254c30f-ab34-49b3-8dc1-64ea940bcdf6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'About the artist'
            type: craft\fieldlayoutelements\Heading
            uid: aac7ffe0-b3b5-4dc0-bd20-94227e394dec
            userCondition: null
          -
            elementCondition: null
            fieldUid: d1f9737c-c74a-4ffd-8fde-fed08a33c48c # Afbeelding 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01d11a1a-0b90-4dd8-ab1e-6fa220df2552
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: cddc48cb-cf17-49ea-96d9-773668a2239f # Beschrijving 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a43268a6-6395-44dd-b777-0b72a689f360
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 60677aed-7d79-4d52-ae45-b2b7e22d5f6d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3c88515a-8032-4a79-94ce-1a74c8074ddf # Toon in navigatie
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec7c9d8b-1583-4155-ba4d-4efc4f5cbb4f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 217fcfdc-f604-49b4-a1d5-be94a3a24296 # Navigatie Afbeelding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 804f1e41-d914-47b5-8cff-4bdf03a9f431
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: dbd11bc6-ad86-4953-959b-f3fb418b6153 # Toon in footer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63c0aab6-8412-4dfe-b328-a687d572f28a
            userCondition: null
            warning: null
            width: 50
        name: Navigatie
        uid: 00b70b2c-c532-49a7-a4d2-809ae70088a4
        userCondition: null
handle: about
hasTitleField: true
name: About
section: 2c1c4276-6b14-4857-8873-c475c0a68f0a # Pagina's
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
