fieldLayouts:
  7cb8d7d6-8619-421b-83ea-2e1937b60db6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8e15f44a-4850-47dd-841c-abb12d15c1c3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8fa4ab2b-d31b-4bd6-b6d8-ee2df12c14e5 # Afbeelding 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75024e1d-a96c-40b7-96cc-5dc0b91e2c92
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a9a6c680-3445-4140-9d53-d27a81b2f7cb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3c88515a-8032-4a79-94ce-1a74c8074ddf # Toon in navigatie
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5fe9886-62c4-47ab-beb3-a79a69b10255
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 217fcfdc-f604-49b4-a1d5-be94a3a24296 # Navigatie Afbeelding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03565a4f-be65-4533-90b1-296aa0134b00
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: dbd11bc6-ad86-4953-959b-f3fb418b6153 # Toon in footer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3964d05-da5b-4091-99bc-465e327c902a
            userCondition: null
            warning: null
            width: 50
        name: Navigatie
        uid: 2bd6669e-8b69-4b33-9d95-3983e4cec5de
        userCondition: null
handle: work
hasTitleField: true
name: Work
section: 2c1c4276-6b14-4857-8873-c475c0a68f0a # Pagina's
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
