dateModified: 1699296919
email:
  fromEmail: $SYSTEM_EMAIL
  fromName: 'Hannah Van der Haeghen'
  replyToEmail: null
  template: null
  transportSettings:
    messageStream: inbound
    token: $POSTMARK_SERVER_TOKEN
  transportType: craftcms\postmark\Adapter
fs:
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: uploads
    type: craft\fs\Local
    url: $UPLOAD_URL
meta:
  __names__:
    0a57c908-5d24-4b0d-a9d4-80615b2cd97f: FAQ # FAQ
    00c5f631-3ba6-4457-8520-81aaf01dbc68: 'Beschrijving 1' # Beschrijving 1
    0d651d0e-b1d7-45ec-a026-bb77e4ababe3: Navigation # Navigation
    0d682bd0-f685-492b-864b-4ce7497f65fb: Detail # Detail
    0f24636c-4f10-4522-894b-45739e075b70: 'Email adres' # Email adres
    1f995a21-6491-4d2d-b126-6b03f6c43a58: 'Filter Groepen' # Filter Groepen
    2c1c4276-6b14-4857-8873-c475c0a68f0a: 'Pagina''s' # Pagina's
    2d03ce61-2ba5-467f-ab56-c487d039e6ec: 'Titel 2' # Titel 2
    02f25b1a-2d32-4626-8ab1-ed9e9f3dae3d: 'Link 1' # Link 1
    3a62f4a6-a4f4-4fad-830a-10a5e8dbdc20: 'Afbeelding plaatsing' # Afbeelding plaatsing
    3c88515a-8032-4a79-94ce-1a74c8074ddf: 'Toon in navigatie' # Toon in navigatie
    3ebf8831-4a21-48bd-a049-493560af4308: Common # Common
    4f3af52d-dc34-45b8-96e8-0355358d1890: About # About
    4fd1bc8c-b3eb-457e-9696-d2ac0b407f4b: Wishlist # Wishlist
    5a5973ce-1c6a-4bd0-abb7-f17fb8cdd368: 'Titel 4' # Titel 4
    5abaf161-4cf4-4485-8e4a-2e257439dda4: 'Form elements (filters, checkboxes, dropdowns)' # Form elements (filters, checkboxes, dropdowns)
    5e45130b-d008-42a5-9107-35670a0d35c3: 'Gallery pagina''s' # Gallery pagina's
    5f5630f3-da19-4241-a164-79bdca4f52f7: 'LinkedIn link' # LinkedIn link
    6fe480a1-4d15-498b-90c0-51adb5580098: 'Uitgelichte producten' # Uitgelichte producten
    7a2f79e4-83dc-4af4-8d09-fc747d840496: 'Unique Combination of Variant Attributes' # Unique Combination of Variant Attributes
    7bfd2eb5-6578-4433-9c41-d19176243b02: 'Contact berichten' # Contact berichten
    7c281d84-4d8d-4b2d-8e36-80a99d919e97: Shop # Shop
    7e733e55-fb42-404f-89bf-858308150e51: Product(en) # Product(en)
    8fa4ab2b-d31b-4bd6-b6d8-ee2df12c14e5: 'Afbeelding 1' # Afbeelding 1
    9a34009d-98d3-4ae0-8dad-b1e0191796ba: Contactbericht # Contactbericht
    9b464eb3-586e-4db0-bf51-3d00017432b0: Nederlands # Nederlands
    9db1f9e4-5692-4c0f-ad4a-c18f1475b2a5: Contact # Contact
    19dc3b2d-a870-4e81-91ff-ebdc5f452c29: Images # Images
    31bb0e04-2a70-4557-8090-a52c1a2254f2: 'Titel 1' # Titel 1
    38e6a148-3a70-43f5-8128-54ff53c63eb2: 'Titel 3' # Titel 3
    47a122e4-5ba5-4021-a156-b23767eb0248: 'Third Party' # Third Party
    48abcf61-f6f1-411b-903a-81f034608b53: Bericht # Bericht
    55a3c65b-7ffe-4e16-b5c0-7e67177ffcf0: Links # Links
    56c3e973-0f59-429a-91ed-318814922bbb: FAQ # FAQ
    87a05afd-1262-47cb-acd2-f6aaed1b9640: Websites # Websites
    94c51b0c-961c-4fd5-904f-5b7871f98cf7: Text # Text
    217fcfdc-f604-49b4-a1d5-be94a3a24296: 'Navigatie Afbeelding' # Navigatie Afbeelding
    239bf23c-88b2-4832-a53e-a335cfc5d124: 'Elements (entries, categories, products)' # Elements (entries, categories, products)
    619a8e46-e785-4b25-90f9-85ba6dcdf9c6: Home # Home
    643cb138-4a82-4f14-a789-948b643043bc: 'Gallery filters' # Gallery filters
    0657cf24-ecbd-4107-adb2-3a4f69e4ad8b: Policy # Policy
    0837baff-b456-4267-8069-08ea42525f09: 'Quote Afbeelding' # Quote Afbeelding
    862eb467-ce26-4fc3-8289-42571aaff556: 'Beschrijving 3' # Beschrijving 3
    958e2e03-63a3-4194-b1cf-ebd5fa9fc895: 'Instagram link' # Instagram link
    4907efcd-d46c-4ebc-aac9-3efb21bb1c18: 'image left' # image left
    7521d7d4-bfee-4451-beed-90ad1d724c5b: Work # Work
    15471e0e-b73a-4c98-94a3-0bb5185f90f2: Shop # Shop
    67748b21-4a3e-47c2-83be-b7ecd539d71c: 'Shop Categorie' # Shop Categorie
    072366a1-39d9-4c91-8e57-6eab946ae6fe: Voornaam # Voornaam
    361382ab-c268-4ec2-a944-660822aea169: English # English
    986126ba-250e-463e-8f3c-3f9257acc84c: 'image right' # image right
    16573316-2b9f-4846-b6f2-ffe2e1a79da7: quote # quote
    a3b7618e-f5d1-4b5f-bd32-db20dd35c26b: SEO # SEO
    a48ddbb3-33df-449b-a3c0-53e95f5b4f88: Wishlist # Wishlist
    a576e86a-698c-4e39-8bb2-f03c1164f56b: 'Variant Attribute Label' # Variant Attribute Label
    a3934515-f94c-4ab0-891d-f8519a8b1561: Assets # Assets
    ab1e9ae1-eba0-4b77-9d5c-752874dc9fbd: 'Filter: shop' # Filter: shop
    ae7f6c08-c9a7-4447-9c37-00e0f870e776: 'General Data' # General Data
    b94dc6c9-aae8-45c7-b754-5f6a3c81039a: 'Facebook link' # Facebook link
    b720bf5f-ae38-4c51-ba44-e85a860129cc: 'Public Schema' # Public Schema
    bba3f6c6-4034-448c-b3b5-62ef276276cd: 'Afbeelding 4' # Afbeelding 4
    c785f0e6-e64a-4275-979b-4b8f8b74ca7a: Achternaam # Achternaam
    c871bcad-3990-4bf3-954f-b29d2e335773: 'Filter: gallery' # Filter: gallery
    cddc48cb-cf17-49ea-96d9-773668a2239f: 'Beschrijving 2' # Beschrijving 2
    d0b4a5be-3377-4fa3-b9aa-3196c601d339: 'Veel gebruikte elementen' # Veel gebruikte elementen
    d1f9737c-c74a-4ffd-8fde-fed08a33c48c: 'Afbeelding 2' # Afbeelding 2
    dbd11bc6-ad86-4953-959b-f3fb418b6153: 'Toon in footer' # Toon in footer
    e6d64dd2-c9e9-410c-81b6-82ffa3358eeb: 'Link 2' # Link 2
    e55f4e6c-f5c8-4f9f-85af-3daf6684a8da: 'Display Type' # Display Type
    e68f4e12-33a8-4163-adbb-26bfa484de3a: Redactor # Redactor
    e71ca281-b0a5-4e2c-8c68-53c0bf3fe520: 'Link 4' # Link 4
    ed335616-6cd9-410b-9d9f-5992c89f02c7: USP # USP
    f016f34d-e9d9-41bf-86cf-5fc0c29b036c: 'Algemene gegevens' # Algemene gegevens
    f2fda0de-15eb-4ada-a4c1-c88f8dc38392: 'Afbeelding 3' # Afbeelding 3
    f3c222fb-a954-43f0-9d6c-a54baae77aa2: 'Link 3' # Link 3
    fe6b4ecc-45d5-44bf-8dbb-dd6b403e53b7: Telefoonnummer # Telefoonnummer
plugins:
  blitz:
    edition: standard
    enabled: false
    licenseKey: K0K7PE1ZFQX1CKMZ7M723N8A
    schemaVersion: 4.4.0
    settings:
      apiKey: ''
      cacheControlHeader: 'public, s-maxage=31536000, max-age=0'
      cacheDuration: null
      cacheElementQueries: true
      cacheElements: true
      cacheGeneratorSettings:
        __assoc__:
          -
            - concurrency
            - '3'
      cacheGeneratorType: putyourlightson\blitz\drivers\generators\HttpGenerator
      cacheNonHtmlResponses: false
      cachePurgerType: putyourlightson\blitz\drivers\purgers\DummyPurger
      cacheStorageSettings:
        __assoc__:
          -
            - folderPath
            - '@webroot/cache/blitz'
          -
            - createGzipFiles
            - ''
          -
            - createBrotliFiles
            - ''
      cacheStorageType: putyourlightson\blitz\drivers\storage\FileStorage
      cachingEnabled: false
      debug: false
      deployerType: putyourlightson\blitz\drivers\deployers\DummyDeployer
      driverJobPriority: 100
      esiEnabled: false
      excludedQueryStringParams:
        -
          __assoc__:
            -
              - queryStringParam
              - gclid
        -
          __assoc__:
            -
              - queryStringParam
              - fbclid
      generatePagesWithQueryStringParams: true
      hintsEnabled: true
      includedQueryStringParams:
        -
          __assoc__:
            -
              - queryStringParam
              - '.*'
      injectScriptEvent: DOMContentLoaded
      integrations:
        - putyourlightson\blitz\drivers\integrations\CommerceIntegration
        - putyourlightson\blitz\drivers\integrations\FeedMeIntegration
        - putyourlightson\blitz\drivers\integrations\SeomaticIntegration
      maxRetryAttempts: 10
      mutexTimeout: 1
      outputComments: true
      purgeAssetImagesWhenChanged: true
      queryStringCaching: 0
      queueJobTtr: 300
      refreshCacheAutomaticallyForGlobals: true
      refreshCacheJobPriority: 10
      refreshCacheWhenElementMovedInStructure: true
      refreshCacheWhenElementSavedNotLive: false
      refreshCacheWhenElementSavedUnchanged: false
      refreshMode: 3
      sendPoweredByHeader: true
      ssiEnabled: false
      trackElementQueries: true
      trackElements: true
  commerce-mollie:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  guest-entries:
    edition: standard
    enabled: true
    schemaVersion: 2.1.0
    settings:
      enableCsrfProtection: '1'
      entryVariable: ''
      sections:
        __assoc__:
          -
            - 7bfd2eb5-6578-4433-9c41-d19176243b02 # Contact berichten
            -
              __assoc__:
                -
                  - sectionUid
                  - 7bfd2eb5-6578-4433-9c41-d19176243b02 # Contact berichten
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - '1'
                -
                  - authorUid
                  - 747476af-ef78-4e7c-87b0-c823cab47c36
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      assetPath: dist
      publicPath: web
  postmark:
    edition: standard
    enabled: true
    schemaVersion: 2.0.1
  quick-field:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  read-only:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 7G0IC4AHSWVI4WSDX11PGUSO
    schemaVersion: 3.0.12
  snaptcha:
    edition: standard
    enabled: true
    licenseKey: Q51UCOX1XSKKXA2GGLDMHDKG
    schemaVersion: 3.0.6
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  wishlist:
    edition: standard
    enabled: false
    licenseKey: KT80JF8CC81ESVD2MG5V6LZA
    schemaVersion: 1.0.5
system:
  edition: pro
  live: true
  name: $SYSTEM_NAME
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: true
  deactivateByDefault: false
  defaultGroup: ''
  photoSubpath: null
  photoVolumeUid: 19dc3b2d-a870-4e81-91ff-ebdc5f452c29 # Images
  requireEmailVerification: true
  validateOnPublicRegistration: false
