defaultPlacement: end
enableVersioning: true
handle: galleryPages
name: 'Gallery pagina''s'
propagationMethod: all
siteSettings:
  9b464eb3-586e-4db0-bf51-3d00017432b0: # Nederlands
    enabledByDefault: true
    hasUrls: true
    template: _pages/entry.twig
    uriFormat: '{parent.uri}/{slug}'
  361382ab-c268-4ec2-a944-660822aea169: # English
    enabledByDefault: true
    hasUrls: true
    template: _pages/entry.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 1
  uid: 133d13c1-90db-4a6c-aa9a-ec4e1270b2c4
type: structure
