name: deploy

on:
  push:
    branches: [ "staging" ]

  # It is important to specify "concurrency" for the workflow,
  # to prevent concurrency between different deploys.
concurrency: staging

jobs:

  deploy:
    name: "Deploy ${{ github.head_ref }}"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install dependencies
        run: composer install

      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.SERVER_DEPLOYMENT_KEY }}
          dep: deploy --branch=${{ github.head_ref }}